<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class tenUsersSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'id' => Str::uuid(),
                'first_name' => 'John',
                'last_name' => 'Doe',
                'sex' => 'Male',
                'birthday' => '1985-06-15',
                'username' => 'johndoe',
                'email' => 'john.doe@itelec3.test',
                'password' => Hash::make('password123'),
                'agreed_to_terms' => true,
                'user_type' => 'Admin',
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => null,
                'verification_token' => Str::random(32),
            ],
            [
                'id' => Str::uuid(),
                'first_name' => 'Jane',
                'last_name' => 'Smith',
                'sex' => 'Female',
                'birthday' => '1990-03-20',
                'username' => 'janesmith',
                'email' => 'jane.smith@itelec3.test',
                'password' => Hash::make('password123'),
                'agreed_to_terms' => true,
                'user_type' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => null,
                'verification_token' => Str::random(32),
            ],
            [
                'id' => Str::uuid(),
                'first_name' => 'Michael',
                'last_name' => 'Brown',
                'sex' => 'Male',
                'birthday' => '1988-08-08',
                'username' => 'mikebrown',
                'email' => 'michael.brown@itelec3.test',
                'password' => Hash::make('password123'),
                'agreed_to_terms' => true,
                'user_type' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => null,
                'verification_token' => Str::random(32),
            ],
            [
                'id' => Str::uuid(),
                'first_name' => 'Emily',
                'last_name' => 'Clark',
                'sex' => 'Female',
                'birthday' => '1992-11-30',
                'username' => 'emilyclark',
                'email' => 'emily.clark@itelec3.test',
                'password' => Hash::make('password123'),
                'agreed_to_terms' => true,
                'user_type' => 'Admin',
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => null,
                'verification_token' => Str::random(32),
            ],
            [
                'id' => Str::uuid(),
                'first_name' => 'David',
                'last_name' => 'Lee',
                'sex' => 'Male',
                'birthday' => '1983-02-18',
                'username' => 'davidlee',
                'email' => 'david.lee@itelec3.test',
                'password' => Hash::make('password123'),
                'agreed_to_terms' => true,
                'user_type' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => null,
                'verification_token' => Str::random(32),
            ],
            [
                'id' => Str::uuid(),
                'first_name' => 'Olivia',
                'last_name' => 'Martinez',
                'sex' => 'Female',
                'birthday' => '1995-09-12',
                'username' => 'oliviam',
                'email' => 'olivia.martinez@itelec3.test',
                'password' => Hash::make('password123'),
                'agreed_to_terms' => true,
                'user_type' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => null,
                'verification_token' => Str::random(32),
            ],
            [
                'id' => Str::uuid(),
                'first_name' => 'Chris',
                'last_name' => 'Wilson',
                'sex' => 'Male',
                'birthday' => '1987-04-25',
                'username' => 'chriswilson',
                'email' => 'chris.wilson@itelec3.test',
                'password' => Hash::make('password123'),
                'agreed_to_terms' => true,
                'user_type' => 'Admin',
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => null,
                'verification_token' => Str::random(32),
            ],
            [
                'id' => Str::uuid(),
                'first_name' => 'Sophia',
                'last_name' => 'Taylor',
                'sex' => 'Female',
                'birthday' => '1993-07-07',
                'username' => 'sophiat',
                'email' => 'sophia.taylor@itelec3.test',
                'password' => Hash::make('password123'),
                'agreed_to_terms' => true,
                'user_type' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => null,
                'verification_token' => Str::random(32),
            ],
            [
                'id' => Str::uuid(),
                'first_name' => 'Liam',
                'last_name' => 'Anderson',
                'sex' => 'Male',
                'birthday' => '1989-01-10',
                'username' => 'liama',
                'email' => 'liam.anderson@itelec3.test',
                'password' => Hash::make('password123'),
                'agreed_to_terms' => true,
                'user_type' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => null,
                'verification_token' => Str::random(32),
            ],
            [
                'id' => Str::uuid(),
                'first_name' => 'Ava',
                'last_name' => 'Walker',
                'sex' => 'Female',
                'birthday' => '1991-10-22',
                'username' => 'avawalker',
                'email' => 'ava.walker@itelec3.test',
                'password' => Hash::make('password123'),
                'agreed_to_terms' => true,
                'user_type' => 'Admin',
                'created_at' => now(),
                'updated_at' => now(),
                'email_verified_at' => null,
                'verification_token' => Str::random(32),
            ],
        ];

        DB::table('usersinfo')->insert($users);
    }
}